# fly.toml app configuration file generated for api-display on 2024-06-17T16:04:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-display'
primary_region = 'atl'
kill_signal = 'SIGTERM'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = '/rel/overlays/bin/migrate.bat'

[env]
  PHX_HOST = 'api-display.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
