name: Tests

on:
  [push, pull_request]
env:
  MIX_ENV: test
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.15.7
    env:
      TEST_API_URL: ${{ secrets.TEST_API_URL }}
      TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: mix deps.get
    - name: Check Formatting
      run: mix format --check-formatted
    - name: Run Tests
      run: mix test
